version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000" # NuxtJS
      - "5000:5000" # Flask
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
    command: yarn dev
